-- Personal data isolation for habit and calendar tracking.
-- Run this in Supabase SQL Editor.

-- Core tables used by the app.
create table if not exists public.calendar_notes (
  date text primary key,
  note text not null default ''
);

create table if not exists public.habit_checks (
  habit text not null,
  date text not null,
  status text not null default 'done',
  primary key (habit, date)
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  updated_at timestamptz not null default now()
);

-- Private list of habits per user.
create table if not exists public.user_habits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  habit_name text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists user_habits_user_habit_name_idx
  on public.user_habits(user_id, habit_name);

-- Add ownership columns.
alter table if exists public.habit_checks
  add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table if exists public.calendar_notes
  add column if not exists user_id uuid references auth.users(id) on delete cascade;

-- Backfill existing rows to current auth user where possible.
-- If multiple users already share data, handle backfill manually before enforcing NOT NULL.
update public.habit_checks
set user_id = auth.uid()
where user_id is null;

update public.calendar_notes
set user_id = auth.uid()
where user_id is null;

-- Enforce ownership for future rows.
alter table if exists public.habit_checks
  alter column user_id set not null;

alter table if exists public.calendar_notes
  alter column user_id set not null;

-- Ensure user-scoped uniqueness.
create unique index if not exists habit_checks_user_habit_date_idx
  on public.habit_checks(user_id, habit, date);

create unique index if not exists calendar_notes_user_date_idx
  on public.calendar_notes(user_id, date);

-- Enable Row Level Security.
alter table if exists public.habit_checks enable row level security;
alter table if exists public.calendar_notes enable row level security;
alter table if exists public.user_habits enable row level security;
alter table if exists public.profiles enable row level security;

-- Replace old policies safely.
drop policy if exists "habit_checks_select_own" on public.habit_checks;
drop policy if exists "habit_checks_insert_own" on public.habit_checks;
drop policy if exists "habit_checks_update_own" on public.habit_checks;
drop policy if exists "habit_checks_delete_own" on public.habit_checks;

drop policy if exists "calendar_notes_select_own" on public.calendar_notes;
drop policy if exists "calendar_notes_insert_own" on public.calendar_notes;
drop policy if exists "calendar_notes_update_own" on public.calendar_notes;
drop policy if exists "calendar_notes_delete_own" on public.calendar_notes;

drop policy if exists "user_habits_select_own" on public.user_habits;
drop policy if exists "user_habits_insert_own" on public.user_habits;
drop policy if exists "user_habits_update_own" on public.user_habits;
drop policy if exists "user_habits_delete_own" on public.user_habits;

drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "profiles_delete_own" on public.profiles;

-- Habit policies.
create policy "habit_checks_select_own"
on public.habit_checks
for select
to authenticated
using (auth.uid() = user_id);

create policy "habit_checks_insert_own"
on public.habit_checks
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "habit_checks_update_own"
on public.habit_checks
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "habit_checks_delete_own"
on public.habit_checks
for delete
to authenticated
using (auth.uid() = user_id);

-- Calendar note policies.
create policy "calendar_notes_select_own"
on public.calendar_notes
for select
to authenticated
using (auth.uid() = user_id);

create policy "calendar_notes_insert_own"
on public.calendar_notes
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "calendar_notes_update_own"
on public.calendar_notes
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "calendar_notes_delete_own"
on public.calendar_notes
for delete
to authenticated
using (auth.uid() = user_id);

-- User habit list policies.
create policy "user_habits_select_own"
on public.user_habits
for select
to authenticated
using (auth.uid() = user_id);

create policy "user_habits_insert_own"
on public.user_habits
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "user_habits_update_own"
on public.user_habits
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "user_habits_delete_own"
on public.user_habits
for delete
to authenticated
using (auth.uid() = user_id);

-- Profile policies.
create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

create policy "profiles_insert_own"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "profiles_delete_own"
on public.profiles
for delete
to authenticated
using (auth.uid() = id);

-- Journal entries table for cross-device sync.
create table if not exists public.journal_entries (
  user_id uuid not null references auth.users(id) on delete cascade,
  date text not null,
  entries jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (user_id, date)
);

alter table if exists public.journal_entries enable row level security;

drop policy if exists "journal_entries_select_own" on public.journal_entries;
drop policy if exists "journal_entries_insert_own" on public.journal_entries;
drop policy if exists "journal_entries_update_own" on public.journal_entries;
drop policy if exists "journal_entries_delete_own" on public.journal_entries;

create policy "journal_entries_select_own"
on public.journal_entries
for select
to authenticated
using (auth.uid() = user_id);

create policy "journal_entries_insert_own"
on public.journal_entries
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "journal_entries_update_own"
on public.journal_entries
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "journal_entries_delete_own"
on public.journal_entries
for delete
to authenticated
using (auth.uid() = user_id);
